ADD index.html and styles.css file
Etsubdink-Demeke/portifolio-setup-and-mobilefirst pull request #1
Opened 2023-04-27 20:34 UTC by Etsubdink-Demeke

This is a pull request for linter setup and adding index.html and styles. filecss file to the project

2023-04-27 22:04 UTC, Olamarx requested changes
Hi @Etsubdink-Demeke, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 22:04 UTC, Olamarx commented on index.html
> +        </div>
- [ ] Since these are links, I would implore you to organize it with ul, then use li for it. In the li, you should a tag so that you can make use of the href, then you can now add the image tag inside the a tag.

2023-04-28 00:26 UTC, BregornOriginal requested changes
Hi @Etsubdink-Demeke  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![hand-sketching-stair-slogan-one-step-closer-chalkboard-79948193](https://user-images.githubusercontent.com/93630700/235021368-f75ce976-2ba3-4deb-8979-ea791fb8f68c.jpg)


 ## Highlights

✅ Linters are passing
✅ Readme looks professional

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 00:26 UTC, BregornOriginal commented on index.html
> +        </div>
Good work adding an `a` tag for each icon

- Kindly, as the previous reviewer requested you, create an `ul` for this list of icons. The structure of this could be something like the following

![image](https://user-images.githubusercontent.com/93630700/235020641-6635f177-a711-418a-9466-59d48cbd638b.png)

2023-04-28 01:27 UTC, Owusu-Desmond approved these changes
Hi @Etsubdink-Demeke , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/NCjISbEPFxm48/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 01:30 UTC, merged